config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.xml { render xml: @kittens }
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to kittens_path
    else
      flash[:danger] = "Could not create kitten"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render xml: @kitten }
      format.json { render json: @kitten }
    end
  end

  def edit
  end

  def update
    if @kitten.update(kitten_params)
      redirect_to kitten_path(@kitten), notice: "Kitten has been succesfully updated"
    else
      flash[:danger] = "Cannot update kitten"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @kitten.destroy
      flash[:success] = "Kitten has been deleted"
      redirect_to kittens_path
    else
      flash[:danger] = "Could not delete kitten "
      redirect_to kittens_path, status: :unprocessable_entity
    end
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<h1>Create Kitten</h1>
<div class="form">
  <% if kitten.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% kitten.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: kitten, local: true, html: { class: 'form-group' }) do |f| %>
    <div class="form_field mb-3">
      <%= f.label :name, class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form_field mb-3">
      <%= f.label :age, class: 'form-label' %>
      <%= f.number_field :age, class: 'form-control' %>
    </div>
    <div class="form_field mb-3">
      <%= f.label :cuteness, class: 'form-label' %>
      <%= f.number_field :cuteness, min: 1, max: 10, class: 'form-control' %>
    </div>
    <div class="form_field mb-3">
      <%= f.label :softness, class: 'form-label' %>
      <%= f.number_field :softness, min: 1, max: 10, class: 'form-control' %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% if kitten.persisted? %>
      <%= link_to "Delete", kitten_path(kitten), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %>
    <% end %>
    <%= link_to "Cancel", root_path, class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/kittens/_kitten.html.erb
<div class="card mb-3">
    <div class="card-body d-flex justify-content-between align-items-center">
        <div>
            <h5 class="card-title mb-0">
      <%= link_to kitten.name, kitten_path(kitten), class: "text-decoration-none" %>
    </h5>
            <p class="card-text mb-0">Age: <%= kitten.age %></p>
            <p class="card-text mb-0">Cuteness: <%= kitten.cuteness %></p>
            <p class="card-text mb-0">Softness: <%= kitten.softness %></p>
        </div>
        <div class="d-flex">
            <%= link_to "Edit", edit_kitten_path(kitten), class: "btn btn-primary me-2" %>
            <%= link_to "Delete", kitten_path(kitten), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger me-2" %>
            <%= link_to "Home", root_path, class: "btn btn-dark" %>
    </div>
  </div>
</div>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<%= render "form",kitten: @kitten %>

app/views/kittens/index.html.erb
<h1>List of all Kittens</h1>
<div>
  <%@kittens.each do |kitten| %>
    <%= render kitten %>
  <% end %>
</div>
<%= link_to "Create",new_kitten_path %>

app/views/kittens/new.html.erb
<%= render "form",kitten: @kitten %>

app/views/kittens/show.html.erb
<%= render "kitten",kitten: @kitten %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <div>
      <%= debug(params).html_safe %>
    </div>
    <div class="flash">
      <% flash.each do |key,value| %>
        <p class="<%=key%>">
          <%= value %>
        </p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>